
global:
  networkInputBufferSize: 102400
  zmqSndBufferSize: 2048
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  
dataUnits:
- type: "modelA"
  ID: "1001"
  ip: "192.168.10.2"
  port: 19555

