
global:
  networkInputBufferSize: 102400
  zmqSndBufferSize: 2048
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  
dataUnits:
#- type: "modelA"
#  ID: "1001"
#  ip: "192.168.10.2"
#  port: 19555
- type: "modelA"
  ID: "2001"
  ip: "192.168.61.24"
  port: 19555
- type: "modelA"
  ID: "2002"
  ip: "192.168.61.53"
  port: 19555
