global:
  networkInputBufferSize: 1024000
  zmqSndBufferSize: 819200
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  t3TriggerTimeCut: 1000000000
  t3TriggerTimeOut: 1000000000
  t3TriggerTimeWindow: 9000
  t3TriggerDuNumber: 4
  # l1FileName: "RUN124_MD_RAW-ChanXYZ-20dB-DU21-10s"
  l1FileName: "RUN150_UD_RAW-ChanXYZ-20dB-DU43-DU59-DU94-XorY-Y2Float-X2Z"
  # l1FileName: "testRUN22_UD_ChanXYZ-20dB-DU43-DU59-DU94-Y2Float-X2Z-CHY-FirmwareV1B-1p1p6p3"
  # l1FileName: "testRUN12_MD_ChanXYZ-20dB-DU18-X2Float-Y2Z-20Hz-FirmwareV1B-1p1p6"
  l3FileName: RUN0914_CD_20dB_11DUs_20Hz_75MHz_BeaconTest
  daqMode: 1
  eventNumberSaved: 10000
dataUnits:
  # - type: modelA
  #   ID: 1021
  #   ip: 192.168.61.21
  #   port: 19555
  # - type: modelA
  #   ID: 1018
  #   ip: 192.168.61.18
  #   port: 19555
  # - type: modelA
  #   ID: 1023
  #   ip: 192.168.61.23
  #   port: 19555
  - type: modelA
    ID: 1043
    ip: 192.168.61.43
    port: 19555
  - type: modelA
    ID: 1059
    ip: 192.168.61.59
    port: 19555  
  - type: modelA
    ID: 1094
    ip: 192.168.61.94
    port: 19555  