global:
  networkInputBufferSize: 102400
  zmqSndBufferSize: 2048
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  t3TriggerTimeCut: 1000000000
  t3TriggerTimeOut: 1000000000
  t3TriggerTimeWindow: 3000
  t3TriggerDuNumber: 3
  # daqMode: 1 is L1-TRIGGER mode, 2 is L3-TRIGGER mode, 3 is BOTH-DATA mode
  daqMode: 1
  eventNumberSaved: 100
  
dataUnits:
#- type: "modelA"
#  ID: "1001"
#  ip: "192.168.10.2"
#  port: 19555
# - type: "modelA"
#   ID: "1010"
#   ip: "192.168.61.10"
#   port: 19555
# - type: "modelA"
#   ID: "1013"
#   ip: "192.168.61.13"
#   port: 19555
# - type: "modelA"
#   ID: "1017"
#   ip: "192.168.61.17"
#   port: 19555
# - type: "modelA"
#   ID: "1019"
#   ip: "192.168.61.19"
#   port: 19555
# - type: "modelA"
#   ID: "1020"
#   ip: "192.168.61.20"
#   port: 19555
# - type: "modelA"
#   ID: "1021"
#   ip: "192.168.61.21"
#   port: 19555
# - type: "modelA"
#   ID: "1029"
#   ip: "192.168.61.29"
#   port: 19555
- type: "modelA"
  ID: "1031"
  ip: "192.168.61.31"
  port: 19555
# - type: "modelA"
#   ID: "1032"
#   ip: "192.168.61.32"
#   port: 19555
# - type: "modelA"
#   ID: "1035"
#   ip: "192.168.61.35"
#   port: 19555
# - type: "modelA"
#   ID: "1041"
#   ip: "192.168.61.41"
#   port: 19555

