global:
  networkInputBufferSize: 1024000
  zmqSndBufferSize: 1024000
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  t3TriggerTimeCut: 1000000000
  t3TriggerTimeOut: 1000000000
  t3TriggerTimeWindow: 14000
  t3TriggerDuNumber: 5
  l1FileName: "RUN149_UD_RAW-ChanXYZ-20dB-DU33-DU44-DU46-XorY-X2X-Y2Y"
  # l1FileName: RUN146_MD_RAW-ChanXYZ-20dB-GP43-20hz-X2FLOAT-Y2Z
  l3FileName: "RUN10071_CD_20dB_23DUs_GP43-ChY-X2X-Y2Y"
  daqMode: 2
  eventNumberSaved: 10000
dataUnits:
# test TCmax 200
  # - type: modelA
  #   ID: 1033
  #   ip: 192.168.61.33
  #   port: 19555
  # - type: modelA
  #   ID: 1044
  #   ip: 192.168.61.44
  #   port: 19555
  # - type: modelA
  #   ID: 1046
  #   ip: 192.168.61.46
  #   port: 19555

  # # - type: modelA
  # #   ID: 1034
  # #   ip: 192.168.61.34
  # #   port: 19555
  # - type: modelA
  #   ID: 1011
  #   ip: 192.168.61.11
  #   port: 19555
  - type: modelA
    ID: 1081
    ip: 192.168.61.81
    port: 19555
  # - type: modelA
  #   ID: 1047
  #   ip: 192.168.61.47
  #   port: 19555
  # # - type: modelA
  # #   ID: 1088
  # #   ip: 192.168.61.88
  # #   port: 19555
  # - type: modelA
  #   ID: 1057
  #   ip: 192.168.61.57
  #   port: 19555
  # - type: modelA
  #   ID: 1051
  #   ip: 192.168.61.51
  #   port: 19555
  # - type: modelA
  #   ID: 1083
  #   ip: 192.168.61.83
  #   port: 19555
  # - type: modelA
  #   ID: 1086
  #   ip: 192.168.61.86
  #   port: 19555
  # - type: modelA
  #   ID: 1089
  #   ip: 192.168.61.89
  #   port: 19555
  # - type: modelA
  #   ID: 1054
  #   ip: 192.168.61.54
  #   port: 19555
  # - type: modelA
  #   ID: 1055
  #   ip: 192.168.61.55
  #   port: 19555
  - type: modelA
    ID: 1032
    ip: 192.168.61.32
    port: 19555
  - type: modelA
    ID: 1077
    ip: 192.168.61.77
    port: 19555
  # - type: modelA
  #   ID: 1042
  #   ip: 192.168.61.42
  #   port: 19555
  - type: modelA
    ID: 1079
    ip: 192.168.61.79
    port: 19555
  - type: modelA
    ID: 1052
    ip: 192.168.61.52
    port: 19555
  - type: modelA
    ID: 1044
    ip: 192.168.61.44
    port: 19555
  # - type: modelA
  #   ID: 109
  #   ip: 192.168.61.9
  #   port: 19555
  - type: modelA
    ID: 1049
    ip: 192.168.61.49
    port: 19555
  - type: modelA
    ID: 1033
    ip: 192.168.61.33
    port: 19555
  - type: modelA
    ID: 1093
    ip: 192.168.61.93
    port: 19555
  - type: modelA
    ID: 1046
    ip: 192.168.61.46
    port: 19555
  - type: modelA
    ID: 1092
    ip: 192.168.61.92
    port: 19555
  - type: modelA
    ID: 1084
    ip: 192.168.61.84
    port: 19555
  - type: modelA
    ID: 1013
    ip: 192.168.61.13
    port: 19555
  - type: modelA
    ID: 1082
    ip: 192.168.61.82
    port: 19555
  - type: modelA
    ID: 103
    ip: 192.168.61.3
    port: 19555
  - type: modelA
    ID: 1020
    ip: 192.168.61.20
    port: 19555
  - type: modelA
    ID: 1075
    ip: 192.168.61.75
    port: 19555
  - type: modelA
    ID: 1029
    ip: 192.168.61.29
    port: 19555
  # - type: modelA
  #   ID: 1031
  #   ip: 192.168.61.31
  #   port: 19555
  - type: modelA
    ID: 1074
    ip: 192.168.61.74
    port: 19555
  - type: modelA
    ID: 1078
    ip: 192.168.61.78
    port: 19555
  - type: modelA
    ID: 1085
    ip: 192.168.61.85
    port: 19555
  # - type: modelA
  #   ID: 1019
  #   ip: 192.168.61.19
  #   port: 19555
  # - type: modelA
  #   ID: 1094
  #   ip: 192.168.61.94
  #   port: 19555
  # - type: modelA
  #   ID: 1014
  #   ip: 192.168.61.14
  #   port: 19555
    
## GP13
  # - type: "modelA"
  #   ID: "1018"
  #   ip: "192.168.61.18"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1023"
  #   ip: "192.168.61.23"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1034"
  #   ip: "192.168.61.34"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1038"
  #   ip: "192.168.61.38"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1040"
  #   ip: "192.168.61.40"
  #   port: 19555
  # # - type: "modelA"
  # #   ID: "1043"
  # #   ip: "192.168.61.43"
  # #   port: 19555
  # - type: "modelA"
  #   ID: "1045"
  #   ip: "192.168.61.45"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1048"
  #   ip: "192.168.61.48"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1058"
  #   ip: "192.168.61.58"
  #   port: 19555
  # # - type: "modelA"
  # #   ID: "1059"
  # #   ip: "192.168.61.59" # mark
  # #   port: 19555
  # # - type: "modelA"
  # #   ID: "1065"
  # #   ip: "192.168.61.65"
  # #   port: 19555
  # - type: "modelA"
  #   ID: "1035"
  #   ip: "192.168.61.35"
  #   port: 19555
  