global:
  networkInputBufferSize: 102400
  zmqSndBufferSize: 81920
  eventBufferPageSize: 1024000
  eventBufferNumberOfPages: 4
  eventBufferPageSize: 2048000
  eventBufferNumberOfPages: 1
  t3TriggerTimeCut: 1000000000
  t3TriggerTimeOut: 1000000000
  t3TriggerTimeWindow: 1500000
  t3TriggerDuNumber: 3
  # l1FileName: "RUN133_MD_RAW_ChanXYZ_20dB_DU58_20Hz_Beacontest_Notchfilter"
  # l1FileName: "RUN133_MD_RAW_20Hz_ChanXYZ_20dB_12DUs"
  l1FileName: "RUN127_UD_RAW_ChanXYZ_20dB_12DUs_"
  # l1FileName: "RUN133_MD_RAW_ChanXYZ_20dB_DU59_20hz"
  l3FileName: "TEST-TRIGGER-ChanY-xxtest_202_June_0dB_DU78_DU74_DU27_RUN1_1024s_chl3_trigger"
  # daqMode: 1 is L1-TRIGGER mode, 2 is L3-TRIGGER mode, 3 is BOTH-DATA mode
  daqMode: 1
  eventNumberSaved: 10000

  
dataUnits:
  # - type: "modelA"
  #   ID: "1009"
  #   ip: "192.168.61.9"
  #   port: 19555
  # - type: "modelA"
  #   ID: "1018"
  #   ip: "192.168.61.18"
  #   port: 19555
  - type: "modelA"
    ID: "1023"
    ip: "192.168.61.23"
    port: 19555
  - type: "modelA"
    ID: "1035"
    ip: "192.168.61.35"
    port: 19555
  - type: "modelA"
    ID: "1038"
    ip: "192.168.61.38"
    port: 19555
  - type: "modelA"
    ID: "1040"
    ip: "192.168.61.40"
    port: 19555
  - type: "modelA"
    ID: "1041"
    ip: "192.168.61.41"
    port: 19555
  - type: "modelA"
    ID: "1043"
    ip: "192.168.61.43"
    port: 19555
  - type: "modelA"
    ID: "1045"
    ip: "192.168.61.45"
    port: 19555
  - type: "modelA"
    ID: "1048"
    ip: "192.168.61.48"
    port: 19555
  # - type: "modelA"
  #   ID: "1058"
  #   ip: "192.168.61.58"
  #   port: 19555
  - type: "modelA"
    ID: "1059"
    ip: "192.168.61.59"
    port: 19555
  - type: "modelA"
    ID: "1065"
    ip: "192.168.61.65"
    port: 19555
